server:
  port: 8081 # 【请根据实际情况填写】可自定义端口，确保不被占用
spring:
  application:
    name: user-service # 给当前微服务起个名字
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 【请根据实际情况填写】如果是部署在云服务器上，填入云服务器的公网IP